services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange-app
    working_dir: /var/www
    env_file: ~/Project/creds/exchange/secrets      
    volumes:
      - .:/var/www
    networks:
      - exchange-network
    depends_on:
      - db
      - redis

  # MySQL Database
  db:
    image: mysql:8
    container_name: exchange-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exchange
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/Users/ankurpareek/Projects/exchange/mysql-data
    networks:
      - exchange-network
    ports:
      - "3333:3306"

  # Redis Service
  redis:
    image: redis:latest
    container_name: exchange-redis
    restart: always
    networks:
      - exchange-network
    ports:
      - "6379:6379"  

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: exchange-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "9090:80"
    depends_on:
      - db
    networks:
      - exchange-network

networks:
  exchange-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
